# fly.toml app configuration file generated for sourdough on 2025-06-24T16:57:30-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sourdough'
primary_region = 'ord'

[build]
dockerfile = 'Dockerfile'

[env]
DB_PATH = '/data/sourdough.db'

[[mounts]]
source = 'sourdough_data'
destination = '/data'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 1024
